Repository prasad-chavan1/python-algos, pull requests merged in 2023-10, with the labels that each got.

#2 Implemented Cycle Sort algorithm in Python
  Sorting/cycle sort.py
Labels: help wanted

#3 added quick sort
  Data Structures - Arrays/Quick Sort.py
Labels: hacktober-fest accepted

#4 Added DFS Traversal for Graph
  Data Structures - Graph/DFS.py
Labels: hacktober-fest accepted

#5 Added BFS Traversal for Graph
  Data Structures - Graph/BFS.py
Labels: hacktoberfest-accepted

#6 readme.md
  Data Structures - Arrays/readme.md
Labels: hacktoberfest-accepted

#10 readme.md
  readme.md
Labels: hacktoberfest-accepted

#9 readme.md
  Data Structures - Linked Lists/readme.md
Labels: hacktoberfest-accepted

#8 readme.md
  Data Structures - Hashtables/readme.md
Labels: hacktoberfest-accepted

#7 readme.md
  Data Structures - Graph/readme.md
Labels: hacktoberfest-accepted

#11 Updated readme for Stack and Queue
  Data Structures - Stacks and Queues/readme.md
  README.md
Labels: hacktoberfest-accepted

#13 Added Shell sort
  Sorting/Shell sort.py
Labels: hacktoberfest-accepted

#14 Added a few Readme's and updated a few.
  Data Structures - Arrays/README.md
  Data Structures - Graph/README.md
  Data Structures - Hashtables/README.md
  Data Structures - Linked Lists/README.md
  Data Structures - Stacks and Queues/README.md
  Data Structures - Trees/Binary Search Tree.py
  Data Structures - Trees/README.md
  Dynamic Programming/README.md
  Recursion/Fibonacci.py
  Recursion/README.md
Labels: hacktoberfest-accepted

#15 Added Queue using Arrays
  Data Structures - Stacks and Queues/Queue using Arrays.py
Labels: hacktoberfest-accepted

#16 Add files via upload
  bellmanford.py
Labels: hacktoberfest-accepted

#17 huffman tree
  Huffman Coding.py
Labels: hacktoberfest-accepted

#18 knapSack
  Knapsack.py
Labels: hacktoberfest-accepted

#20 Dijkstra's algo
  Dijkstra’s  algorithm.py
Labels: hacktoberfest-accepted
